### ISSUE TITLE
`Uniform::new called with `low >= high`

### ISSUE THREAD

**Issue by ChristopherRabotin** [Martin1887/oxigen#21]
**Describe the bug**
Oxigen fails to create the next generation of individuals.

**To Reproduce**
I'm not sure how to reproduce it with a simple use case, but I can reproduce it systematically with a small variation to the [orbit_design_ga](https://gitlab.com/nyx-space/showcase/orbit_design_ga/) project. Specifically, if my genome is only one gene long, this problem shows up. Two or more genes, and it doesn't happen.

I understand/expect that the information I provide is not enough to fix. Hence, can you explain to me in which cases the following line from `crossover.rs` would fail:

```
let cross_point = SmallRng::from_entropy().sample(Uniform::from(1..ind_size));
```

I'm guessing that `ind_size` is zero, but I don't know what would cause it to be zero.

Thanks for your help

**Stack trace**

```
     Running `target/debug/orbit_design_ga`
Fitness: 2000
Fitness: 2001
Fitness: 2001
Fitness: 2001
Fitness: 2000
Fitness: 2001
Fitness: 2000
Fitness: 2001
Fitness: 0
Fitness: 0
Fitness: 0
Fitness: 2000
Fitness: 2001
Fitness: 2000
Fitness: 2001
Fitness: 2001
thread 'main' panicked at 'Uniform::new called with `low >= high`', /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.7.3/src/distributions/uniform.rs:477:1
stack backtrace:
   0: std::panicking::begin_panic
             at /home/chris/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: <rand::distributions::uniform::UniformInt<usize> as rand::distributions::uniform::UniformSampler>::new
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.7.3/src/distributions/uniform.rs:379:17
   2: rand::distributions::uniform::Uniform<X>::new
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.7.3/src/distributions/uniform.rs:172:17
   3: <rand::distributions::uniform::Uniform<X> as core::convert::From<core::ops::range::Range<X>>>::from
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.7.3/src/distributions/uniform.rs:272:9
   4: <oxigen::crossover::CrossoverFunctions as oxigen::crossover::Crossover<T,G>>::cross
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/oxigen-2.2.0/src/crossover.rs:31:67
   5: oxigen::GeneticExecution<T,Ind>::cross::{{closure}}
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/oxigen-2.2.0/src/lib.rs:639:40
   6: core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call
             at /home/chris/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:237:13
   7: <rayon::iter::map_with::MapWithFolder<C,U,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::with::{{closure}}
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/map_with.rs:317:22
   8: core::iter::adapters::map::map_fold::{{closure}}
             at /home/chris/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:80:28
   9: core::iter::traits::iterator::Iterator::fold
             at /home/chris/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2023:21
  10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /home/chris/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:120:9
  11: core::iter::traits::iterator::Iterator::for_each
             at /home/chris/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:678:9
  12: <rayon::iter::noop::NoopConsumer as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/noop.rs:34:9
  13: <rayon::iter::map_with::MapWithFolder<C,U,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/map_with.rs:322:25
  14: rayon::iter::plumbing::Producer::fold_with
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/plumbing/mod.rs:110:9
  15: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/plumbing/mod.rs:438:13
  16: rayon::iter::plumbing::bridge_producer_consumer
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/plumbing/mod.rs:397:12
  17: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/plumbing/mod.rs:373:13
  18: <rayon::range::Iter<usize> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/range.rs:112:17
  19: rayon::iter::plumbing::bridge
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/plumbing/mod.rs:357:12
  20: <rayon::range::Iter<usize> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/range.rs:88:17
  21: <rayon::iter::map_with::MapWith<I,T,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/map_with.rs:53:9
  22: rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<()> for ()>::from_par_iter
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/from_par_iter.rs:226:9
  23: rayon::iter::ParallelIterator::collect
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/mod.rs:1973:9
  24: rayon::iter::ParallelIterator::for_each_with
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/mod.rs:400:9
  25: oxigen::GeneticExecution<T,Ind>::cross
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/oxigen-2.2.0/src/lib.rs:626:9
  26: oxigen::GeneticExecution<T,Ind>::run_loop
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/oxigen-2.2.0/src/lib.rs:345:36
  27: oxigen::GeneticExecution<T,Ind>::run
             at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/oxigen-2.2.0/src/lib.rs:311:49
  28: orbit_design_ga::main
             at ./src/main.rs:32:9
  29: core::ops::function::FnOnce::call_once
             at /home/chris/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Martin1887** [comment]
Hello.

In this case `ind_size` is not 0 but 1 (the individual size) and `rand` fails to generate a number between 1 and lower than 1 (since the maximum is not included in the possible values when using this function).

This happens because the single crosspoint crossover tries to generate a crosspoint in the middle of the individual (nor the start nor the end, since this would generate identical individuals). The same happens for multicrosspoint crossover but with several points.

Note that having individuals of size 1 is very rare. To solve this issue in your scenario you can choose uniform crossover, that will work fine because it does not generate crosspoints but puts each gene of a different individual (note that this will happen until the shortest individual last index). Generally, it is not a good idea having individuals of different length, but sometimes it can be acceptable.

Anyway, I will release a new version with more descriptive error messages in single crosspont and multicrosspoint and fixing that with individuals of different length and uniform crossover the individuals are reduced to the size of the smallest one instead of remaining without changes in the rest of genome (I have just noticed it).


Thanks.

**Comment by Martin1887** [comment]
A new version has just been published with the fixes in uniform crossover and more descriptive error messages when the length of the shortest individual is 0 or 1.


Regards.

**Comment by Martin1887** [comment]
I have been thinking about crosspoint crossovers with 1 gene individuals and a new release has just been launched handling this special case: the gene is interchanged with a random position of the bigger individual (note that if both individuals are of length 1 then children are identical to parents). Therefore, you can use single crosspoint and multicrosspoint crossovers with 1 gene individuals now.

This release also changes uniform crossover to cross random positions instead of even ones.


Regards.
